README.md, src/top/utop.el
These changes were sparked by the discussion on #87.
Additionally I was hitting a bug when using the babel feature in org-mode. The previous implementation would mess with the `*-interactive-buffer-name` variable which stopped babel from being able to evaluate my OCaml code in my code blocks.
Please note that this is a breaking-change for emacs users as they will need to change their configuration given that `utop-setup-ocaml-buffer` has been deleted.
=> Refactor major mode use

src/top/utop.el
Emacs does not have 'replace-in-string' function. You can see this by byte-compiling.
```
In end of data:
utop.el:1258:1:Warning: the function `replace-in-string' is not known to be defined.
```
=> Fix non-exist function

src/lib/uTop.ml
- Behavior is identical
- Makes utop forward compatible with merged PR 595 of ocaml trunk
Also it is shorter
=> Replace handwritten ppf with Format.formatter_of_buffer call

src/lib/uTop.ml, src/lib/uTop.mli, src/lib/uTop_history.ml, src/lib/uTop_history.mli, src/lib/uTop_main.ml
I picked up @chrismamo1's progress and added the remaining bits:
- Stripping of colour escapes
- Separate inputs and outputs in the stashable history
- Another directive besides `#utop_stash`: `#utop_save`, which saves the session as if it was entered in a simplified prompt:
```
val x : int = 5
val y : int = 6
- : int = 11
Error: This expression has type int but an expression was expected of type
string
Error: Syntax error
```
Warnings are omitted currently, but I don't consider this a vital feature.
=> Stashing updated

CHANGES.md, src/lib/uTop.ml, src/lib/uTop.mli, src/lib/uTop_main.ml
This rewrites toplevel expressions like `x;;` to `let _n = x;;`, for example:
```ocaml
val x : int = 5
val _1 : int = 11
val _2 : int = 5
```
Only tested on 4.04. I think this is the right approach. The newly created bindings are not available in the output of `#utop_stash`, but I think this unavoidable.
Currently the binding (`val _1 : …`) only shows up if `-show-reserved` is passed. We could show `_n` when `n` is numeric even when reserved identifiers should be hidden.
=> Bind expressions to _0, _1, etc.

src/top/utop.el
Include the necessary hooks for phrase detection in Reason.
We'll need to wait on: https://github.com/facebook/reason/pull/1227
This is the configuration that I use at the moment:
```
(add-hook 'reason-mode-hook
(lambda ()
(utop-minor-mode)
(define-key utop-mode-map (kbd "C-<up>") 'utop-history-goto-prev)
(define-key utop-mode-map (kbd "C-<down>") 'utop-history-goto-next)
(setq utop-command "opam config exec -- rtop -emacs")))
```
I was wondering if the `utop-command` should be set by `utop.el`. What do you think?
=> Add support for Reason (native)

jbuild
seems that was forgotten in the migration to jbuild. Unfortunately, this causes 'opam-user-setup' to break badly (at emacs startup, it finds the opam package, then breaks trying to load the file, and consequently doesn't load remaining modules)
=> Fix installation to handle utop.el too

utop.opam
Right now it's being pulled transitively from zed, but it's being used directly
in utop
=> Add camomile dep to utop

src/lib/uTop_main.ml
The handler for 'utop -vnum' failed to terminate after printing the
version number.
=> Fix utop -vnum

.gitignore, src/top/utop.el
I got rid of all the old Emacs workarounds. Emacs 24 is 5 years old, it's a
reasonable minimum. Also cleaned up a bunch of code that is more tersely done
with ocaml like pattern matching (pcase, which is available for emacs >= 24).
Finally, I've hacked together a simple company backend for utop completion. It's
not really ready for merging, but if there's interest I can work on it further.
For example: make the old completion still available for those who don't
use/like company, add type signatures to completions.
I've found it easier to implement the completion by adding a simple completion
command in utop itself. Although that might because I don't quite understand all
the details in the old command. Would appreciate some comments here.
=> Some random work I did on the emacs mode

src/top/utop.el
tuareg-next-phrase was moved to tuareg_indent.el in
ocaml/tuareg@b40e733c1 and removed entirely in
ocaml/tuareg@b2ad75f3d5 (September 2017).
As a result, utop-eval-phrase crashes due to the missing function.
Instead, write a small function to move to the next phrase, similar to
the movement logic in tuareg-eval-phrase.
=> Fix utop-eval-phrase on recent tuareg-mode

src/top/utop.el
Change the company backend to only work on utop buffers, otherwise it does not passes control to the next backend
=> Company backend only complete on utop buffers

src/lib/uTop_main.ml
This PR makes utop automatically install as printer all functions marked with `[@@ocaml.toplevel_printer]`  in mli files. This gives a very simple way for users to define new toplevel printers.
=> Automatically install printers marked with [@@ocaml.toplevel_printer]

src/lib/uTop.ml, src/lib/uTop_lexer.mll, src/lib/uTop_main.ml
note, this pr depends on another pr in the lambda-term project ocaml-community/lambda-term#71
* UTop_lexer: support combined glyph
* follow the api changes of zed_char and zed_string
=> unicode support improvements: wider glyph, combined glyph

src/top/dune
Fix the typo introduced in 7e8567682dc4e8126d4f6c6bd4f4e9673a87de6e.
=> Fix typo: mode -> modes

src/lib/uTop.ml, src/lib/uTop.mli, src/lib/uTop_complete.ml, src/lib/uTop_complete.mli, src/lib/uTop_lexer.mli, src/lib/uTop_lexer.mll, src/lib/uTop_main.ml, src/top/utop.el
Despite camlp4 and camlp5 mentioned as removed in 2.0.0 version https://github.com/ocaml-community/utop/blob/master/CHANGES.md#200-2016-05-26, camlp4 syntax still handled in the code. Removing the clutter then. See also https://github.com/ocaml-community/utop/issues/289 issue.
=> Remove camlp4 remnants

src/top/utop.el
A recent commit deleted the variable utop-ocaml-preprocessor in utop.el, but there are still some references to that variable, causing the error
`Symbol’s value as variable is void: utop-ocaml-preprocessor`
This pull request deletes the remaining references to utop-ocaml-preprocessor.
=> Remove now-broken elisp that depends on utop-ocaml-preprocessor

CHANGES.md
* Remove camlp4 remnants (@XVilka, #290) (@kandu, #293)
* Allow to statically link utop (@diml, #285) (@hongchangwu, #286)
* Remove broken elisp (m-plamann, #292)
* Add OCaml 4.08 build in Travis CI (XVilka, #291)
=> release 2.4.1

src/lib/uTop_main.ml
This PR fixes the compilation with OCaml 4.09:
- The use of `Obj.truncated` for overriding `Sys.argv` is replaced by a call to `caml_sys_modify_argv`
- Iteration on the typed tree is implemented with `Tast_iterator` rather than `TypedtreeIter`.
- Loading persistent signature is done with `Persistent_env.Persistent_signature`
Closes #298
=> Fixes for 4.09

.travis.yml
OCaml 4.09 and 4.10 are not tested by your CI. This PR fixes that.
This PR is for now a draft as it relies on https://github.com/ocaml/ocaml-ci-scripts/pull/320 to be able to test 4.10.0beta1 but should be mergeable as soon as it gets merged.
=> Add OCaml 4.09 and 4.10.0+beta1 to the CI matrix

CHANGES.md, src/lib/uTop.ml
I added a `#use_output` directive in the trunk of OCaml (https://github.com/ocaml/ocaml/pull/9283). I propose to backport this feature in utop so that it is available to users of OCaml < 4.11.
=> Backport the #use_output directive from OCaml 4.11

src/lib/uTop.ml, src/lib/uTop.mli, src/lib/uTop_main.ml
Add two new directive: edit_mode_default and edit_mode_vi to trigger vi edit mode. resolve #136
This PR depends on ocaml-community/lambda-term/pull/85
=> Vi edit mode

CHANGES.md, utop.opam
2.6.0 (2020-05-30)
------------------
* compatible with OCaml 4.11 (@kit-ty-kate, #322)
* switch to the new parser exposed since 4.11
* vi_edit_mode: register support
=> release 2.6.0

src/lib/uTop_main.ml
With OCaml 4.12.0 and later, the toplevel uses the Compenv.Exit_with_status exception to communicate when and with which status we should exit.
This PR makes use of this information which should avoid the fatal error reported in #345.
close #345
=> OCaml 4.12.0: exit with the right exit status

src/top/utop.el
`tuareg--after-double-colon` no longer exists in the latest rev of
Tuareg, so inline the old definition, which was removed in
commit 91ba1d6143558092a3920e9b5c49755c0c86caed of Tuareg.
`tuareg--skip-double-colon` was renamed to `tuareg--skip-double-semicolon`. Also inline this, to avoid depending on a private function.
=> utop.el: Fix utop-tuareg-next-phrase for newer tuareg.el

src/top/utop.el
If `utop-edit-command` is nil, then `utop-query-arguments` returns nil.
This breaks `utop-restart` which relies upon it returning the right arguments.
`utop-query-arguments` always returns `(utop-arguments)` whether it sets the utop-command or not.
=> Utop correctly restarts when (not utop-edit-command)

src/lib/uTop.ml, src/lib/uTop.mli, src/lib/uTop_main.ml
The output from the compiler changed and now mentions the line number
(non only the charters, which actually becomes columns). This patch
introduces the idea of a range of lines spanned by an error and
correctly marks the faulty region.
I think a better solution would be to introduce a "point" record of
the form {line:int;column:int}. However, such a change would
reverberate through all the source code and so it is much more
invasive. I can prepare such a patch if desired, after this one, which
fixes the regression.
This was tested with OCaml 4.11.2 and 4.12.
Fixes #349
=> Fix color highlight for errors.

src/lib/uTop_main.ml
fixes: #333, #325
this `if...else` clause can be bypassed entirely if we don't automatically source `.ocamlinit` in the current project directory and instead pass it as `-init` explicitly.
Not sure what's the default expected ocaml toplevel behaviour though.
=> Make sure we're not at $HOME before sourcing local .ocamlinit

src/lib/uTop.ml, src/lib/uTop_complete.ml, src/lib/uTop_main.ml
Changes came from https://github.com/ocaml/ocaml/pull/10124 as well as https://github.com/ocaml/ocaml/pull/10207
Only 300dd7e is strictly necessary to build utop on OCaml 4.13.
=> Add support for OCaml 4.13

man/utop.1
Add all options as decribed by the output by --help to the manual page.
This was done manually and some automation would be nicer.
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>
=> Document utop(1) options in manual page

src/lib/uTop_main.ml
ocaml/ocaml#10893 removed the flag `unsafe_string` in the upcoming OCaml 5.
=> Remove -safe-string for OCaml 5. See ocaml/ocaml#10893

src/lib/uTop.ml, src/lib/uTop_main.ml
Smaller version of https://github.com/ocaml-community/utop/pull/376 without the `Utop.load_otherlibs` part. Additional OCaml PR incoming to aid it as well.
=> Support new Load_path.init API

README.md
The readme states
> 'Key bindings in the terminal can be changed by writing a ~/.lambda-term-inputrc file. For example:'
However, after writing this file and then exiting utop after it's next restart generates the below warning:
```Warning: it is recommended to move `/home/owen/.lambda-term-inputrc` to `$XDG_CONFIG_HOME`, see:
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html```
=> Update README.md with correct filepath.

README.md
This avoids hard to maintain duplication.
=> Doc: only mention dependencies in the opam file

src/lib/dune, src/lib/uTop.ml, src/lib/uTop_main.ml, utop.opam
This updates utop to use the uu packages instead of camomile, following ocaml-community/zed#46 and ocaml-community/lambda-term#109.
=> Compatibility with zed 3.2.0

src/lib/dune, src/lib/uTop_main.ml, src/lib/uTop_styles.ml, utop.opam
The latter is deprecated and incompatible with OCaml 5.0.
=> Use logs.lwt instead of lwt_logs

src/top/utop.el
Without those changes you won't get any completion for things like
"List.m". I'm not very familiar with the code, but it seems that the
backend returns the completion candidates without the module prefix
which caused the problem.
I've opted to fix this by handling prefixes with a "." in them specially
and this works fine in the limited testing I conducted locally.
=> [Fix #358] Fix code completion for module identifiers in utop.el

README.md, src/top/utop.el
Those are extremely common in Emacs modes and allow people to
quickly jump to a REPL and back to the last source buffer they
were editing, while using the same keybinding.
I've modeled the implementation here after that of inf-clojure (a similar
mode written by me). I've also implemented a mode menu for
utop-minor-mode, so it's easier for the users to discover its
functionality.
=> Add commands to switch to and from a utop buffer

src/lib/uTop.mli, src/top/utop.el
When point is at the letter "n" in
utop[1]> let thi[n]g = 42
and the user presses C-j, it is always because they want to terminate
the expression at the end-ish of the input.
The unpatched behavior did not move point, and inserted two semicolons
in the middle of the expression.
=> utop.el: always insert phrase terminator at the end-ish of input

CHANGES.md, src/lib/uTop_main.ml
Exiting normally here refers to the `Exit_with_status` exception. It is in particular triggered by `#quit;;` so we want to exit quietly in that case.
Closes #398
=> Do not display a backtrace when exiting normally

CHANGES.md, src/lib/uTop.mli, src/lib/uTop_main.ml
They have been deprecated in 2012 and most of them are ignored.
=> Mark deprecated values with attribute

src/lib/uTop.ml, src/lib/uTop_compat.ml, src/lib/uTop_complete.ml, src/lib/uTop_main.ml
The utop code base is full of `#if OCAML_VERSION` to adapt to the changes in `compiler-libs`.
This has some issues - for example the corresponding logic is harder to recognize, and some logic is duplicated in several places. Also, this prevents using a formatter.
One medium-term goal is to move most of the compat functions to a new `Utop_compat` module which would be the only place we use `cppo`.
This PR contains the "easy" cases - moving existing functions, etc. It is a bit more difficult (and controversial) to convert pattern matching to this pattern so it'll be done in a separate PR.
While doing that, several cases of duplications were found so this explains the negative diffstat.
=> Move compat functions to their module

README.md
Both Alt-TAB and Alt-Down already work in utop. But in many OSes, Alt-Tab is reserved for switching windows. Moreover, once your fingers are on LEFT/RIGHT, I think having to move to TAB is not practical. So I think that it makes more sense to advertise ALT-down in the README file.
=> use M-down instead of M-tab

src/lib/uTop_compat.ml, src/lib/uTop_main.ml
This adds support for OCaml 5.1.
=> OCaml 5.1 support

CHANGES.md, src/lib/uTop.ml, src/lib/uTop_main.ml
We are building a hidden expression that contains "()" but it is not
qualified. So it will pick the constructor in scope. This can cause
problems if `()` has been redefined. The correct fix is to qualify it as
part of the `Unit` module.
(additionally, this removes an unused ident)
Fixes #417
=> Qualify () constructor

CHANGES.md, src/top/utop.el
After poking around for ways to use my normal `completion-at-point` workflow in the utop buffer, I came accross issue #261, which is a feature request to provide a completion-at-point-fuction.
This is an implementation I came up with that works for me and I wanted to share it here in case anyone else found it useful or had any feedback.
=> Add completion-at-point implementation ocaml-community/utop#261

CHANGES.md, src/lib/uTop.ml
Fixes #428
The change in #418 introduced a regression if a `Unit` module in scope does not have a `()` constructor in it.
This switches to the more explicit `Stdlib.Unit.()` path.
=> fix regression with unit qualification

src/lib/uTop_compat.ml
See issue #433 for how the problem showed itself.
In 4.14 the behavior of Toploop.use_silently changed. Previously, the empty string would be interpreted as a request for Stdin. Now File and Stdin are different constructors of Toploop.input.
This PR adds logic to the wrapper already used to use the File constructor to select Stdin when the filename passed is the empty string.
NB this means that `utop -stdin` works but `utop ""` has the same effect, which AFAICT was the behavior pre-4.14 but may not be desirable.
=> Fix behavior of utop -stdin

src/lib/uTop.ml, test/test_lib.ml
Fixes https://github.com/ocaml-community/zed/issues/57
=> Check that `Zed.next_error` index value is within the string length

CHANGES.md, README.md, dune-project, src/lib/dune, src/lib/uTop.ml, src/lib/uTop_private.ml, src/lib/uTop_styles.ml, utop.opam, utoprc-dark, utoprc-light
This PR adds support for the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) by moving the `~/.utop-history` and `~/.utoprc` files to `$XDG_CACHE_HOME/utop-history` and `$XDG_CONFIG_HOME/utop/utoprc` respectively.
Both of these changes still support fallbacks to their original locations to not introduce a strict backwards incompatibility.
While this history file should really be saved as `$XDG_STATE_HOME/utop-history`, the XDG state directory is currently unsupported in the current version of lambda-term. I have filed a PR to that project [here](https://github.com/ocaml-community/lambda-term/pull/113) to add the functionality for downstream use here.
This PR improves on #362 by utilizing the existing dependency on …
=> XDG Base Directory Compliance

CHANGES.md, src/top/dune
Without this commit, you get:
```
File "src/top/dune", line 33, characters 0-131:
33 | (rule
34 |  (targets utop-expunged.bc)
35 |  (action
36 |   (run %{ocaml_where}/expunge %{dep:utop.bc} %{targets}
37 |     %{read-lines:modules.txt})))
Error: File unavailable:
Z:/source/dkml/build/pkg/bump/.ci/o/PR/lib/ocaml/expunge
```
=> Fix unavailable expunge on Windows

README.md
The $ prevented the lines from being copied, and run as they are.
=> Make installation instructions run as shown

README.md
"opam config var" was deprecared in version 2.1 and generates an error message in the process output:
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
Prevents evaluating to invalid load-path components:
```elisp
(add-to-list
'load-path
(replace-regexp-in-string
"\n" "/share/emacs/site-lisp"
(shell-command-to-string "opam config var prefix")))
(car load-path)
```
evaluates to:
```
"[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0./share/emacs/site-lisp/home/juergen/.opam/default/share/emacs/site-lisp"
```
=> Use "opam var" instead "opam config var"

CHANGES.md, dune-workspace.dev, src/lib/uTop.ml, src/lib/uTop_compat.ml, src/lib/uTop_complete.ml, src/lib/uTop_main.ml
Hi folks! I saw Sabine's tweet and I figured I'd give this a shot. There's a few things that I'd like to upstream to the compiler (like Ast_helpers to create function params), but otherwise this seems to be working.
Happy to amend anything here, just figured I'd open the PR early to get feedback / directions.
Ideally would close #466
=> Support OCaml 5.2

src/lib/uTop_main.ml
An [old ocaml commit](https://github.com/ocaml/ocaml/commit/3efba04eb34e914b0a032b90f67ca42e202315f6) moved ``Clflags.debug := true`` from the module initalisation to their ``loop`` function, which we do not call.
So this adds the same just before calling the main (recursive) ``loop`` function in utop, both in normal and emacs mode.
Closes #501.
And then we get good backtraces :
```
─( 09:21:33 )─< command 0 >──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────{ counter: 0 }─
utop # let rec f (h::t) = h + f t;;
Line 1, characters 10-16:
Warning 8 [partial-match]: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
[]
val f : int list -> int = …
```
=> Adding Clflags.debug before main loop, as in Toploop

src/lib/uTop.ml, src/lib/uTop_compat.ml, src/lib/uTop_complete.ml, src/lib/uTop_main.ml
This PR adds support for OCaml 5.4 by adding new compatibility functions to `uTop_compat`.
=> OCaml 5.4 support

src/lib/uTop_main.ml, src/lib/uTop_private.ml
Issue #481 described failure to load utoprc from its stated location
PR #475 misidentified the issue as an incorrect README
In fact the paths were pointing to files within the XDG base directories themselves rather than in a subdirectory for the utop application.
This patch simply changes $XDG_STATE_HOME/utop-history to $XDG_STATE_HOME/**utop**/utop-history and $XDG_CONFIG_HOME/utoprc to $XDG_CONFIG_HOME/**utop**/utoprc
=> Correct paths for utop-history, utoprc: in utop subdirs of XDG base dirs

src/top/utop.el
Fixes a mismatch of the completion START position in the Emacs buffer and the candidatates that didn't include the expected module-prefix.
Fixes #455
=> Emacs completion: Include module prefix in completion candidates
