- src/lib/uTop_main.ml
UTop ran ppx preprocessors for the "input" command but not for the "input-multi" command. As a result, Emacs `utop-eval-buffer` and `utop-eval-region` functions, which send the "input-multi" command to UTop, did not work with  ppx rewriters, such as `ppx_deriving`.
This commit makes UTop run ppx preprocessors for both of the two commands.
Fix #192
> Run ppx preprocessors for both "input" and "input-multi" commands

- src/lib/uTop.ml
- src/lib/uTop_complete.ml
- src/lib/uTop_main.ml
UTop does not support OCaml < 4.02 anymore.
> Simplify #if directives

- src/top/utop.el
The patch tries to improve on the current way of evaluating a phrase and
skipping to the next. It removes both `utop-skip-to-end-of-phrase` and
`utop-skip-blank-and-comments`, but adds `utop-next-phrase-beginning`.
We assume `utop-discover-phrase` is always returning the end position as
at end of a `;;`. Thereafter we use `utop-next-phrase-beginning` to skip
to the next phase if `utop-skip-after-eval-phrase` is non-nil.
> Refactor hooks for better handling of phrase eval, closes #201.

- .travis.yml
- examples/custom-utop/jbuild
- examples/interact/jbuild
- jbuild-workspace.dev
- src/lib/jbuild
- src/lib/uTop.ml
- src/top/expunge/jbuild
- src/top/jbuild
- utop.descr
- utop.opam
@pmetzger if you'd like to help out. Please this branch out.
> 4.06.0 and safe string

- README.md
- utop.descr
This is to help newcomers and stems from the discussion
https://discuss.ocaml.org/t/ocaml-first-impressions/517/47
> Make clear that toplevel = REPL

- src/lib/uTop_main.ml
- src/top/utop.el
@tuncer if you use company mode, would you mind giving this branch a try?
> Company mode

- src/lib/uTop_complete.ml
This is not the _right_ fix.  It just allows `make` to complete.
> Minimal update to make utop build on OCaml 4.07.0+rc1

- CHANGES.md
- jbuild-workspace.dev
- pkg/pkg.ml
* dune-release
* changelog
* workspace file update
> Release update

- dune-project
- src/lib/uTop.ml
- src/lib/uTop.mli
- src/lib/uTop_complete.ml
- src/lib/uTop_main.ml
- src/lib/uTop_styles.ml
- utop.opam
Basically rebase of https://github.com/ocaml-community/utop/pull/246
> Fix deprecated warnings

- README.md
From `diml` to `ocaml-community`
> Update a link in Readme.md

- README.md
- man/utop.1
This is in the Prompt section of README.md.  I'm submitting a separate PR for an analogous change to the man page so you can easily reject one PR and accept the other if you want.
> Added tips for simple prompt without fancy features

- src/lib/uTop_lexer.mll
After PR #290 was merged, there are still some remnants left in the lexer.
cc @XVilka
> remove more camlp4 remnants

- src/lib/uTop.ml
- src/lib/uTop_complete.ml
- src/lib/uTop_main.ml
This PR makes utop compatible with 4.10, resolves #304 
No significant changes, only some naming tweaks are made
> compatible with 4.10

- README.md
> Add documentation for dune utop usage in emacs

- .travis.yml
- src/lib/uTop_complete.ml
- src/lib/uTop_main.ml
Fixes https://github.com/ocaml-community/utop/issues/321. cc @kandu
> OCaml 4.11 support

- CHANGES.md
- src/lib/uTop_complete.ml
- src/lib/uTop_main.ml
* use the exposed parser to parse longident
see also #301
> compatible with ocaml 4.11

- src/lib/uTop_main.ml
On 4.12, `Typemod.type_structure` does not take a location argument anymore (see ocaml/ocaml#9974). This fixes the build with the 4.12 branch.
> Fix build on 4.12

- src/top/utop.el
In standalone mode, utop returns all the possible completions when no
one matches what the user has typed. This is surprising in emacs
because of the different UI/UX. For this reason, we keep a list of
prefixes for which completion has started and return only the
candidates which match the prefixes.
Fixes: #343
> Fix emacs completion returning bogus candidates.

- man/utop.1
Point to utop --help for the list of options and explain --require in
particular.
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>
> Update OPTIONS section in utop manual page

- src/lib/uTop_main.ml
Provides compatibility with the proposed change in ocaml/ocaml#11199
> Adapt to new mechanism for loading topdirs.cmi

- src/lib/uTop.ml
> Handle Syntaxerr.Removed_string_set

- CHANGES.md
- src/lib/uTop.ml
- src/lib/uTop_complete.ml
- src/lib/uTop_main.ml
- utop.opam
Utop supports a wide range of OCaml versions, but this is getting more difficult to support. In addition, some of the dependencies we use do not support 4.03-4.07, so utop can not be built on these versions.
> Bump the compat to 4.08+

- src/top/utop.el
One of my previous PRs passed CI when I pushed, but failed CI once it got merged. This should fix the issue.
> Shut up Emacs 29's byte-compiler

- examples/custom-utop/dune
- examples/interact/dune
- src/lib/dune
- src/top/dune
- src/top/expunge/dune
> Do not pass -safe-string explicitly

- CHANGES.md
- src/lib/uTop.ml
- src/lib/uTop.mli
- src/lib/uTop_main.ml
Follow-up to #415: we remove these values.
> Remove deprecated values

- README.md
- man/utop.1
- man/utoprc.5
No material changes, just editorial fixes
> Fixed some minor typos in the README and man pages

- .github/workflows/build-dune.yml
This introduces a workflow for dune package management. It would help us ensure the package builds with dune developer preview.
> Add a dune package management GHA workflow
